### ISSUE TITLE
Clickable welcome/goodbye messages

### ISSUE THREAD

**Issue by Bloodlex** [Btd20/customwelcome#1]
Hey,

Could you make such a feature, so players could click the joining/leaving text and then it would write a greeting/farewell from that player who clicked it into the chat? 🙂 

Thanks a lot.

**Comment by Btd20** [comment]
Yeah! I hope to have it ready in a few hours. Thanks for the suggestion.

**Comment by Btd20** [comment]
Hi, i can't do that feature, i tried but it's difficult to implement it on the plugin. Thanks for the suggest anyways :)
