### ISSUE TITLE
It seems that "player_name" is not working.

### ISSUE THREAD

**Issue by creeper-0910** [Btd20/customwelcome#2]
Environment: Paper 1.19-538
After installation, when I log in, the message is displayed, but the player name does not seem to be displayed correctly.
Sorry if this is a PaperMC issue.
![スクリーンショット 2023-05-20 214116](https://github.com/Btd20/customwelcome/assets/56744841/02507bad-e02b-40f1-b7f0-3179b8d2f0ed)

**Comment by creeper-0910** [comment]
It appears that it was necessary to run `/papi ecloud download Player`
Is there a statement explaining this? My apologies if I have missed it.

**Comment by Btd20** [comment]
My fault, I recently updated the spigot page and accidentally deleted the command to unload the variable.

**Comment by creeper-0910** [comment]
I see.
Thanks for the quick reply and correction!

**Comment by Btd20** [comment]
I have already changed the spigot page, thanks for reporting the error :)
